### ISSUE TITLE
`git move --merge` followed by `git rebase --continue` fails to move branch names

### ISSUE THREAD

**Issue by nyanpasu64** [arxanas/git-branchless#255] opened 2022-01-16 11:07 UTC
### Description of the bug

I'm using `git move` in a branch-based workflow. When I run `git move -d REF`, it updates all branches attached to those commits and leaves me checked out to the same branch as before. When this would result in a merge conflict, and I instead run `git move -d REF --merge`, I run into a merge conflict in a rebase operation. When I fix the conflict and run `git rebase --continue`, it prints `Successfully rebased and updated detached HEAD.`, leaves me checked out to a detached HEAD, and the branches don't actually move.

### Expected behavior

`git move --merge` works properly with branches, and moves the branches and leaves me checked out at the initial branch.

### Version of `git-branchless`

git-branchless 0.3.8 as well as `cargo install --git https://github.com/arxanas/git-branchless.git`

**Comment by arxanas** [comment] 2022-01-18 07:30
Hi @nyanpasu64, thanks for your report. I was able to reproduce this issue.

Probably the biggest reason this wasn't caught by an automated test is that most of them render the smartlog to confirm the structure of the commit graph, but the smartlog currently doesn't differentiate between a detached HEAD and having a branch checked out.I added a few tests with explicit checks for the currently-checked-out branch in https://github.com/arxanas/git-branchless/pull/251, but evidently they weren't enough to catch this situation. I think it would be good to add a specific glyph to the smartlog output to indicate the currently-checked-out branch, if any.

**Comment by nyanpasu64** [comment] 2022-01-18 09:06
> the smartlog currently doesn't differentiate between a detached HEAD and having a branch checked out

When I encountered the issue, not only did HEAD become detached and the current branch not move with HEAD, but other branches (in my case, attached to ancestors of HEAD) didn't move either. Can your proposed unit tests catch all of these issues?

Personally I'd use `git log --graph --oneline` rather than (or alongside) smartlog, when testing branch-based workflows. (I don't like how `--graph --oneline` *sometimes* inserts blank lines between commits. There might be a command which either *always* or *never* inserts blank lines between commits; I think [prezto's glg alias](https://github.com/sorin-ionescu/prezto/blob/979144d0e490c3f130f430e99154e3d2ce063d94/modules/git/alias.zsh) inserts 1 or 2 blank lines between commits.)

Sidenote, I find `git move`'s flags (`-b/-d/-s`) unintuitive, and I'm not sure how to explicitly include/exclude parent/sibling branches, so I keep trying random commands until I find something that works (or move more branches than I wanted by mistake, oops). Is there a graphical preview or interactive mode, or is it too difficult to implement?

**Comment by arxanas** [comment] 2022-01-18 17:10
> When I encountered the issue, not only did HEAD become detached and the current branch not move with HEAD, but other branches (in my case, attached to ancestors of HEAD) didn't move either. Can your proposed unit tests catch all of these issues?

In principle, these issues should have already been caught,  since they don't depend on the attached-ness of HEAD. If you have specific cases beyond the one reported here, feel free to file additional bug reports.

> Personally I'd use git log --graph --oneline rather than (or alongside) smartlog

That's a good idea. I also didn't like that most of the tests didn't have a dependency on the smartlog rendering. Hopefully the rendering is consistent between Git versions.

> Sidenote, I find git move's flags (-b/-d/-s) unintuitive, and I'm not sure how to explicitly include/exclude parent/sibling branches, so I keep trying random commands until I find something that works (or move more branches than I wanted by mistake, oops).

The general rule should be that if a branch points to a commit, and that commit is moved, then the branch moves "along with" the commit (i.e. points to the new version of the commit). In practice, most of the bugs probably arise from on-disk rebases, because of how we integrate with Git. (For example, we always detach HEAD before starting an on-disk rebase, and then try to fix up the old branch later for various technical reasons. In practice, maybe you would see "successfully updated detached HEAD" even when the branch *has* been updated?)

> Is there a graphical preview or interactive mode, or is it too difficult to implement?

I would love to have an interactive mode, but it's too much work at present. I'm also curious: do you primarily use a terminal or GUI editor? I was thinking to make an interactive mode extension for VS Code (my primary editor), so that things like clicking-and-dragging are more reasonable.

For an interactive mode, there are also a bunch of cool things that could be done, like pre-computing rebases and surfacing whether a given commit can be moved without causing a merge conflict.

**Comment by arxanas** [comment] 2022-02-01 01:37
@nyanpasu64 Actually, it turns out I was using an old version of git-branchless distributed through Homebrew for testing, so when I tested, I was using v0.3.8, which still had the bug. It seems to already be fixed on the latest build from source. Can you confirm that you're running the latest git-branchless from source (i.e. `cargo install --locked git-branchless` and then check that`which -a git-branchless` shows an entry like `/Users/Waleed/.cargo/bin/git-branchless` at the top) and that the issue persists?

**Comment by KevinWuWon** [comment] 2022-02-08 10:59
Might be worth rolling a new release so people don't need to build from source to get this fix?

**Comment by arxanas** [comment] 2022-02-08 17:10
@KevinWuWon agreed, pushed a new release v0.3.9.

@nyanpasu64 I'm closing this now under the assumption that I couldn't reproduce it because the issue was fixed. Please reopen with repro steps if you're still encountering this issue after upgrading.

**Closed by arxanas** 2022-02-08 17:10 UTC
Labels: bug
