### ISSUE TITLE
Git submit does not with a password-protected RSA key

### ISSUE THREAD

**Issue by slymon99** [arxanas/git-branchless#721] opened 2022-12-30 20:50 UTC
### Description of the bug

```
$ git submit
branchless: running command: git fetch origin
Enter passphrase for key MYKEY: ⠁ Running Git command: git fetch origin 
⠒ Running Git command: git fetch origin (2.1s)                                               
branchless: running command: git push --force-with-lease origin branch1 branch2
⠙ Pushing branches (0.0s)                                           ░░░░░░░░░░░░░░░░░░░░ 0/3 
⠙ Pushing branches (3.0s)                                           ░░░░░░░░░░░░░░░░░░░░ 0/3 
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Failed to push branches: branch1, branch2
```
Submit starts to run before I've typed in my keys password and fails.

If I copy `git push --force-with-lease origin branch1 branch2` into my command line (i.e. run the same command through git), everything works fine.

### Version of `git-branchless`

git-branchless-opts 0.7.0-pre.1

### Version of `git`

git version 2.39.0

**Comment by arxanas** [comment] 2022-12-31 06:50
Thanks for reporting. This looks similar to https://github.com/arxanas/git-branchless/issues/433. Do you think the prompting is happening during `git fetch` or `git push`?

In my case, I use `ssh-agent` and `ssh-add -K /path/to/key` (on macOS) to unlock the key, and then `git sync --pull` works for me. Does that workaround work for you?

**Comment by slymon99** [comment] 2023-01-17 16:42
Sorry for the late response - yes that workaround works for me. The prompting is happening during git fetch

**Comment by arxanas** [comment] 2023-01-18 20:29
I'll close this issue as a duplicate of https://github.com/arxanas/git-branchless/issues/721. I wasn't able to find a good workaround (see the issue description there); if you have any ideas, post them on the issue.

**Closed by arxanas** 2023-01-18 20:29 UTC
Labels: bug
