### ISSUE TITLE
I have this problem when switching branches

### ISSUE THREAD

**Issue by ghost** [arxanas/git-branchless#1381] opened 2024-08-08 17:26 UTC
### Description of the bug

I installed it via Homebrew. I have problems switching between branches.
<img width="1799" alt="Screenshot 2024-08-09 at 00 20 20" src="https://github.com/user-attachments/assets/91e304f7-276a-48a3-bba9-3c62f11f0820">

### Version of `rustc`

rustc 1.80.0 (051478957 2024-07-21)

### Version of `git-branchless`

git-branchless-opts 0.9.0

### Version of `git`

git version 2.46.0

**Comment by arxanas** [comment] 2024-10-09 12:39
Closing as duplicate of https://github.com/arxanas/git-branchless/issues/1388; follow there for updates.

**Closed by arxanas** 2024-10-09 12:39 UTC
Labels: bug
