### ISSUE TITLE
`git amend` crashes when amending a submodule revision change 

### ISSUE THREAD

**Issue by leocencetti** [arxanas/git-branchless#798] opened 2023-02-15 08:39 UTC
### Description of the bug

I am using `git branchless` on a repository that contains some sub-modules. I am using `git branchless` also inside those sub-modules. My directory structure is something like this:
```bash
.
└─ main_repo
    ├─ .git
    ├─ some_files.txt
    └─ submodule_1
        ├─ .git
        └─ some_other_files.txt
```
If I checkout `submodule_1` at a different revision, stage the revision update in `main_repo` and call `git amend` (still in `main_repo`), `git branchless` crashes.

### Expected behavior

`git amend` should update the previous commit and not crash

### Actual behavior

```bash
user@laptop:~/Workspace/PX4-Autopilot$ git amend
The application panicked (crashed).
Message:  A fatal error occurred: 
   0: could not create working copy snapshot: could not create blob from Tools/sitl_gazebo: cannot create blob from '/home/user/Workspace/PX4-Autopilot/Tools/sitl_gazebo': it is a directory; class=Odb (9)
   1: could not create blob from Tools/sitl_gazebo: cannot create blob from '/home/user/Workspace/PX4-Autopilot/Tools/sitl_gazebo': it is a directory; class=Odb (9)
   2: cannot create blob from '/home/user/Workspace/PX4-Autopilot/Tools/sitl_gazebo': it is a directory; class=Odb (9)

Location:
   /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/git-branchless-0.6.0/src/commands/amend.rs:63

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Location: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/git-branchless-0.6.0/src/commands/mod.rs:464

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

<details>
    <summary>Full Rust Backtrace</summary>

```bash
The application panicked (crashed).
Message:  A fatal error occurred: 
   0: could not create working copy snapshot: could not create blob from Tools/sitl_gazebo: cannot create blob from '/home/user/Workspace/PX4-Autopilot/Tools/sitl_gazebo': it is a directory; class=Odb (9)
   1: could not create blob from Tools/sitl_gazebo: cannot create blob from '/home/user/Workspace/PX4-Autopilot/Tools/sitl_gazebo': it is a directory; class=Odb (9)
   2: cannot create blob from '/home/user/Workspace/PX4-Autopilot/Tools/sitl_gazebo': it is a directory; class=Odb (9)

Location:
   /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/git-branchless-0.6.0/src/commands/amend.rs:63

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 3 frames hidden ⋮                               
   4: git_branchless::commands::amend::amend::h46e175a9b9fa1e7d
      at <unknown source file>:<unknown line>
   5: git_branchless::commands::do_main_and_drop_locals::h2b9a7c3a06957e2b
      at <unknown source file>:<unknown line>
   6: git_branchless::commands::main::hcf5e1a5eecebe358
      at <unknown source file>:<unknown line>
   7: std::sys_common::backtrace::__rust_begin_short_backtrace::h7a8867a368569986
      at <unknown source file>:<unknown line>
   8: std::rt::lang_start::{{closure}}::h6edd2698d6440ecd
      at <unknown source file>:<unknown line>
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha0ec212ab4f77f16
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/core/src/ops/function.rs:259
  10: std::panicking::try::do_call::h48607f7552c924c2
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panicking.rs:492
  11: std::panicking::try::h3160b7d5b765f2dc
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panicking.rs:456
  12: std::panic::catch_unwind::h15dc3d510a1565a5
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panic.rs:137
  13: std::rt::lang_start_internal::{{closure}}::h8251d7c301e52521
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/rt.rs:128
  14: std::panicking::try::do_call::h621f5a74981e2493
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panicking.rs:492
  15: std::panicking::try::h19e8eec73d818e1d
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panicking.rs:456
  16: std::panic::catch_unwind::h445c334789a64dcc
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panic.rs:137
  17: std::rt::lang_start_internal::h0b83bd2f4c5c32a0
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/rt.rs:128
  18: main<unknown>
      at <unknown source file>:<unknown line>
  19: __libc_start_main<unknown>
      at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308
  20: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Location: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/git-branchless-0.6.0/src/commands/mod.rs:464

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 8 frames hidden ⋮                               
   9: core::result::Result<T,E>::expect::h5538ebe53cf4f397
      at <unknown source file>:<unknown line>
  10: git_branchless::commands::main::hcf5e1a5eecebe358
      at <unknown source file>:<unknown line>
  11: std::sys_common::backtrace::__rust_begin_short_backtrace::h7a8867a368569986
      at <unknown source file>:<unknown line>
  12: std::rt::lang_start::{{closure}}::h6edd2698d6440ecd
      at <unknown source file>:<unknown line>
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha0ec212ab4f77f16
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/core/src/ops/function.rs:259
  14: std::panicking::try::do_call::h48607f7552c924c2
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panicking.rs:492
  15: std::panicking::try::h3160b7d5b765f2dc
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panicking.rs:456
  16: std::panic::catch_unwind::h15dc3d510a1565a5
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panic.rs:137
  17: std::rt::lang_start_internal::{{closure}}::h8251d7c301e52521
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/rt.rs:128
  18: std::panicking::try::do_call::h621f5a74981e2493
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panicking.rs:492
  19: std::panicking::try::h19e8eec73d818e1d
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panicking.rs:456
  20: std::panic::catch_unwind::h445c334789a64dcc
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/panic.rs:137
  21: std::rt::lang_start_internal::h0b83bd2f4c5c32a0
      at /build/rustc-8kCV4J/rustc-1.61.0+dfsg1~llvm/library/std/src/rt.rs:128
  22: main<unknown>
      at <unknown source file>:<unknown line>
  23: __libc_start_main<unknown>
      at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308
  24: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

</details>

### Version of `rustc`

rustc 1.61.0

#### Software version

git-branchless 0.6.0

#### Operating system

Linux 5.15.0-58-generic

#### Command-line

```bash
/home/user/.cargo/bin/git-branchless bug-report 
```

#### Environment variables

```bash
SHELL=/bin/bash
EDITOR=<not set>
```

#### Git version

```
> git version 
git version 2.39.1
```

#### Hooks

<details>
<summary>Show 6 hooks</summary>

##### Hook `post-commit`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-commit "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-merge`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-merge "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-rewrite`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-rewrite "$@"
## END BRANCHLESS CONFIG
```
##### Hook `post-checkout`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-post-checkout "$@"
## END BRANCHLESS CONFIG
```
##### Hook `pre-auto-gc`

```
#!/bin/sh
## START BRANCHLESS CONFIG

git branchless hook-pre-auto-gc "$@"
## END BRANCHLESS CONFIG
```
##### Hook `reference-transaction`

```
#!/bin/sh
## START BRANCHLESS CONFIG

# Avoid canceling the reference transaction in the case that `branchless` fails
# for whatever reason.
git branchless hook-reference-transaction "$@" || (
echo 'branchless: Failed to process reference transaction!'
echo 'branchless: Some events (e.g. branch updates) may have been lost.'
echo 'branchless: This is a bug. Please report it.'
)
## END BRANCHLESS CONFIG
```

</details>

#### Events

<details>
<summary>Show 5 events</summary>

##### Event ID: 23, transaction ID: 18 (message: hook-post-rewrite)

1. `RewriteEvent { timestamp: 1676392882.332543, event_tx_id: EventTransactionId(18), old_commit_oid: 9351d58babf9b18f71fa73ad20844b7b1d01efb6, new_commit_oid: 44e249012fd6f1993dfef25a90dbaffc09c37a0d }`
```
:
O 0270c20 22d (main) xxxx xxx xxxxxxxx xxxxxxxxxxxx xxx xxxxxx xxxxxx
|
o 0cd55a9 17h xxx xxxx x xxxxxx xxxxx xxxxx
|
o a623cf6 16h xxxxx xxxx xxxxx xx xxxxxxxxx xxxxx
|
@ 44e2490 15h (redacted-ref-0) xxxxx xxx xxxxx
```
##### Event ID: 22, transaction ID: 17 (message: post-commit)

1. `CommitEvent { timestamp: 1676392880.0, event_tx_id: EventTransactionId(17), commit_oid: NonZeroOid(44e249012fd6f1993dfef25a90dbaffc09c37a0d) }`
```
:
O 0270c20 22d (main) xxxx xxx xxxxxxxx xxxxxxxxxxxx xxx xxxxxx xxxxxx
|
o 0cd55a9 17h xxx xxxx x xxxxxx xxxxx xxxxx
|
o a623cf6 16h xxxxx xxxx xxxxx xx xxxxxxxxx xxxxx
|
@ 44e2490 15h (redacted-ref-0) xxxxx xxx xxxxx
```
##### Event ID: 20, transaction ID: 16 (message: reference-transaction)

1. `RefUpdateEvent { timestamp: 1676392882.2995708, event_tx_id: EventTransactionId(16), ref_name: ReferenceName("HEAD"), old_oid: 9351d58babf9b18f71fa73ad20844b7b1d01efb6, new_oid: 44e249012fd6f1993dfef25a90dbaffc09c37a0d, message: None }`
1. `RefUpdateEvent { timestamp: 1676392882.2995708, event_tx_id: EventTransactionId(16), ref_name: ReferenceName("refs/heads/redacted-ref-0"), old_oid: 9351d58babf9b18f71fa73ad20844b7b1d01efb6, new_oid: 44e249012fd6f1993dfef25a90dbaffc09c37a0d, message: None }`
```
:
O 0270c20 22d (main) xxxx xxx xxxxxxxx xxxxxxxxxxxx xxx xxxxxx xxxxxx
|
o 0cd55a9 17h xxx xxxx x xxxxxx xxxxx xxxxx
|
o a623cf6 16h xxxxx xxxx xxxxx xx xxxxxxxxx xxxxx
|
@ 44e2490 15h (redacted-ref-0) xxxxx xxx xxxxx
```
##### Event ID: 19, transaction ID: 15 (message: hook-post-rewrite)

1. `RewriteEvent { timestamp: 1676392509.5413554, event_tx_id: EventTransactionId(15), old_commit_oid: 1a50f76f6ab9df482392e8c21aee082179806b72, new_commit_oid: 9351d58babf9b18f71fa73ad20844b7b1d01efb6 }`
```
:
O 0270c20 22d (main) xxxx xxx xxxxxxxx xxxxxxxxxxxx xxx xxxxxx xxxxxx
|
o 0cd55a9 17h xxx xxxx x xxxxxx xxxxx xxxxx
|
o a623cf6 16h xxxxx xxxx xxxxx xx xxxxxxxxx xxxxx
|
@ 44e2490 15h (redacted-ref-0) xxxxx xxx xxxxx
```
##### Event ID: 18, transaction ID: 14 (message: post-commit)

1. `CommitEvent { timestamp: 1676392508.0, event_tx_id: EventTransactionId(14), commit_oid: NonZeroOid(9351d58babf9b18f71fa73ad20844b7b1d01efb6) }`
```
:
O 0270c20 22d (main) xxxx xxx xxxxxxxx xxxxxxxxxxxx xxx xxxxxx xxxxxx
|
o 0cd55a9 17h xxx xxxx x xxxxxx xxxxx xxxxx
|
o a623cf6 16h xxxxx xxxx xxxxx xx xxxxxxxxx xxxxx
|
@ 44e2490 15h (redacted-ref-0) xxxxx xxx xxxxx
```

</details>

**Comment by arxanas** [comment] 2023-02-15 18:02
Hi @leocencetti, thanks for reporting. This is a limitation of the implementation for `git amend`: it always takes a "snapshot" as part of the amend process, and snapshotting submodules is not currently supported. You can find more discussion here: https://github.com/arxanas/git-branchless/issues/517#issuecomment-1235993786

For now, I would recommend you use `git commit --amend` for the problematic submodule cases. I'm closing this issue as a duplicate of #517.

**Closed by arxanas** 2023-02-15 18:02 UTC
Labels: bug
