### ISSUE TITLE
scm-diff-editor cannot select empty files when using 'jj split'

### ISSUE THREAD

**Issue by thoughtpolice** [arxanas/git-branchless#995] opened 2023-07-14 21:03 UTC
### Description of the bug

I'm using `jj` to develop and `scm-diff-record` as my editor for splits, etc. When I `jj split` a working copy commit that contains an empty file, I can't select that file in the diff editor.

Repro steps:

1. `jj new main`
2. touch empty.txt
3. echo > not-empty.txt
4. `jj split`
5. You can select `not-empty.txt`, but not `empty.txt` to be included in the first commit.

### Expected behavior

I should be able to select `empty.txt` to included in the original commit during `jj split`.

### Actual behavior

I cannot select the file at all.

**Comment by arxanas** [comment] 2023-07-14 21:21
Makes sense, this can't actually happen in git-branchless since untracked new files can't be included in the commit and tracked new files have to be marked as staged (erroneously, not currently detected correctly) but git-branchless doesn't support partial commit selection on staged files. The intended behavior was that a "file mode" section would appear, indicating a transition from mode 000 to 644, etc.

**Comment by arxanas** [comment] 2023-07-30 22:29
@thoughtpolice can you try with #1013?

> The intended behavior was that a "file mode" section would appear, indicating a transition from mode 000 to 644, etc.

For now, I've just made it so that selecting no changes in this file causes the file not to be included at all. This is slightly suboptimal — there's no way to request that the `split` operation creates the file but adds no contents — but, from the existing operation of `hg crecord`, I think this doesn't matter too often in practice.

**Comment by thoughtpolice** [comment] 2023-07-31 16:48
Yeah, I'll try to test it sometime this week. Thanks!

**Closed** 2023-08-03 01:06 UTC
Labels: bug
