### ISSUE TITLE
v0.7.1 isn't on cargo

### ISSUE THREAD

**Issue by alan-nf** [arxanas/git-branchless#897] opened 2023-04-12 02:59 UTC
### Description of the bug

[v0.7.1](https://github.com/arxanas/git-branchless/releases/tag/v0.7.1) looks released here on github but doesn't seem to be on [cargo](https://crates.io/crates/git-branchless).

**Comment by arxanas** [comment] 2023-04-18 02:46
I'm not exactly sure why this is happening, but there's a dependency "cycle" of `git-branchless-lib (dev)` -> `git-branchless-testing` -> `git-branchless-lib`, and I can't get `cargo publish` to publish the packages:

```
$ cargo publish -p git-branchless-lib            
    Updating crates.io index
   Packaging git-branchless-lib v0.7.1 (/Users/Waleed/Workspace/git-branchless/git-branchless-lib)
error: failed to prepare local package for uploading

Caused by:
  no matching package named `git-branchless-testing` found
  location searched: registry `crates-io`
  required by package `git-branchless-lib v0.7.1 (/Users/Waleed/Workspace/git-branchless/git-branchless-lib)`

$ cargo publish -p git-branchless-testing
    Updating crates.io index
warning: manifest has no description, license, license-file, documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
   Packaging git-branchless-testing v0.7.1 (/Users/Waleed/Workspace/git-branchless/git-branchless-testing)
   Verifying git-branchless-testing v0.7.1 (/Users/Waleed/Workspace/git-branchless/git-branchless-testing)
error: failed to verify package tarball

Caused by:
  failed to select a version for the requirement `git-branchless-lib = "^0.7.1"`
  candidate versions found which didn't match: 0.7.0, 0.6.0, 0.5.0, ...
  location searched: crates.io index
  required by package `git-branchless-testing v0.7.1 (/Users/Waleed/Workspace/git-branchless/target/package/git-branchless-testing-0.7.1)`
  ```
  
I'm happy to add you as an owner on crates.io if you want to try publishing it yourself 🙂. For me, the issue reproduces by running

```
$ cargo publish -p git-branchless-lib --dry-run
```

which shouldn't need publishing permissions to start.

**Comment by arxanas** [comment] 2023-09-21 01:43
Closing since v0.8 is out. I had to undo the circular dependency altogether.

**Closed by arxanas** 2023-09-21 01:43 UTC
Labels: bug, no-planned-fix
