### ISSUE TITLE
git-move: panics when `--dest` has not been observed by the `Dag`

### ISSUE THREAD

**Issue by cormacrelf** [arxanas/git-branchless#129] opened 2021-10-18 12:46 UTC
I'm working on the rust-lang/rust repo, I was about to do a rebase onto ~300 new commits and thought I'd try git-move. I know that some git-branchless ops can't work out of the box (eg undo), but given the blog post I figured you could use it to replace git rebase in any situation. Alas:

```
$ git branchless init
...
$ git show-ref master
1067e2ca5e9cfe5c79f956e49ffc684c5142d49b refs/heads/master
5dab47dcd8267b8769421b46532414ec36d625e3 refs/remotes/origin/master
$ git status -sb
## let-else-typed...fork/let-else-typed
$ git move --dest origin/master
The application panicked (crashed).
Message:  A fatal error occurred:
   0: Sorting DAG vertex set
   1: 5dab47dcd8267b8769421b46532414ec36d625e3 cannot be found
```

The branch I'm rebasing is at 38ba92f0 in my fork, which is 26 commits ahead of 1067e2ca, and it can be found at https://github.com/cormacrelf/rust/tree/git-move-issue.

It did work fine when I pulled master from origin and then tried to rebase onto the local master. I wonder if this would have worked if I never initialized branchless at all, perhaps it's a thing with the database not having been populated yet.

I don't know how the whole config.mainBranch thing fits in, but I would have expected this to work without switching to the main branch (on disk), pulling from the remote (writing to disk) and switching back to the branch I wanted to rebase (again, on disk) before running this tool in-memory. As you can see, this bug kinda defeats the purpose of git-move's fully in-memory execution. Is there perhaps a way to `pull --rebase` without checking out the local branch in question, by hooking in to `git-move`? I'd love that as a feature, having to switch to master just to fetch new commits is such a chore.

<details>
<summary>Full backtrace</summary>

(Unfortunately I don't know how to make this run without terminal colour escapes, surely the backtrace code should recognise it's being piped to a file and not a terminal like every other program. Copy paste this into a file and cat it in a terminal, should be fine.)

```
[31mThe application panicked (crashed).[0m
Message:  [36mA fatal error occurred: 
   0: [91mSorting DAG vertex set[0m
   1: [91m5dab47dcd8267b8769421b46532414ec36d625e3 cannot be found[0m

Location:
   [35m/Users/cormac/.cargo/registry/src/github.com-1ecc6299db9ec823/git-branchless-0.3.6/src/git/dag.rs[0m:[35m295[0m

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: [91mbranchless::git::dag[0m[91m::[0m[91mget_one_merge_base_oid[0m with [96mself=<Dag> effects=<Output fancy=false> repo=<Git repository at: "/Users/cormac/src/rust/.git/"> lhs_oid=NonZeroOid(38ba92f0a5a8f21654cb8d703ccd189c1e378264) rhs_oid=NonZeroOid(5dab47dcd8267b8769421b46532414ec36d625e3)[0m
      at [35m/Users/cormac/.cargo/registry/src/github.com-1ecc6299db9ec823/git-branchless-0.3.6/src/git/dag.rs[0m:[35m283[0m
       281 │     /// Get one of the merge-base OIDs for the given pair of OIDs. If there are
       282 │     /// multiple possible merge-bases, one is arbitrarily returned.
  [37m[1m     283 >     #[instrument][0m
       284 │     pub fn get_one_merge_base_oid(
       285 │         &self,
   1: [91mbranchless::commands::r#move[0m[91m::[0m[91mr#move[0m with [96meffects=<Output fancy=false> git_run_info=<GitRunInfo path_to_git="git" working_directory="/Users/cormac/src/rust" env=not shown> source=None dest=Some("origin/master") base=None force_in_memory=false force_on_disk=false dump_rebase_constraints=false dump_rebase_plan=false[0m
      at [35m/Users/cormac/.cargo/registry/src/github.com-1ecc6299db9ec823/git-branchless-0.3.6/src/commands/move.rs[0m:[35m53[0m
        51 │ 
        52 │ /// Move a subtree from one place to another.
  [37m[1m      53 > #[instrument][0m
        54 │ pub fn r#move(
        55 │     effects: &Effects,

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: [32mbacktrace::backtrace::trace[0m[90m::h5608b8ea1a3751f8[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   2: [91mbacktrace::capture::Backtrace::new[0m[90m::h1f6af8d01ff5ea6a[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   3: [91mcolor_eyre::config::EyreHook::into_eyre_hook::{{closure}}[0m[90m::hbfabfada0ef6eec4[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   4: [91meyre::capture_handler[0m[90m::h84ba1e2b9d0c5215[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   5: [91mbranchless::git::dag::Dag::get_one_merge_base_oid[0m[90m::hcce384447c7a36ae[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   6: [91mbranchless::commands::move::move[0m[90m::h185ffd76af77df07[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   7: [91mbranchless::commands::do_main_and_drop_locals[0m[90m::hcd01fa7028bf8ecc[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   8: [91mbranchless::commands::main[0m[90m::h31fe288b2b696b9f[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   9: [32mstd::sys_common::backtrace::__rust_begin_short_backtrace[0m[90m::h9013f4972cfd1e23[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
  10: [32mstd::rt::lang_start::{{closure}}[0m[90m::hea3f1e3cb83db06d[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
  11: [32mcore::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once[0m[90m::h8403429a622a77b6[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/core/src/ops/function.rs[0m:[35m259[0m
  12: [32mstd::panicking::try::do_call[0m[90m::hb3300ca68d979c3c[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m403[0m
  13: [32mstd::panicking::try[0m[90m::h99079dac8dd742de[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m367[0m
  14: [32mstd::panic::catch_unwind[0m[90m::h5c82c9202c92574b[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panic.rs[0m:[35m129[0m
  15: [32mstd::rt::lang_start_internal::{{closure}}[0m[90m::h4b4d3cec192fefc5[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/rt.rs[0m:[35m45[0m
  16: [32mstd::panicking::try::do_call[0m[90m::hb7097b4c5e2cafa7[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m403[0m
  17: [32mstd::panicking::try[0m[90m::h8058a26d87d74c3d[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m367[0m
  18: [32mstd::panic::catch_unwind[0m[90m::he5cdfef2bb12186b[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panic.rs[0m:[35m129[0m
  19: [32mstd::rt::lang_start_internal[0m[90m::h33c6249c3be62eca[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/rt.rs[0m:[35m45[0m
  20: [32m_main[0m[90m<unknown>[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.[0m
Location: [35m/Users/cormac/.cargo/registry/src/github.com-1ecc6299db9ec823/git-branchless-0.3.6/src/commands.rs[0m:[35m262[0m

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: [32mbacktrace::backtrace::trace[0m[90m::h5608b8ea1a3751f8[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   2: [91mbacktrace::capture::Backtrace::new[0m[90m::h1f6af8d01ff5ea6a[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   3: [91mcolor_eyre::config::PanicHook::panic_report[0m[90m::h1069a93ac7607968[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   4: [91mcolor_eyre::config::PanicHook::into_panic_hook::{{closure}}[0m[90m::h71db4435396e7cf4[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
   5: [32mstd::panicking::rust_panic_with_hook[0m[90m::he6c6413666d55a62[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m628[0m
   6: [32mstd::panicking::begin_panic_handler::{{closure}}[0m[90m::h055eac394d0553ff[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m521[0m
   7: [32mstd::sys_common::backtrace::__rust_end_short_backtrace[0m[90m::hb0938709617b3c2b[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/sys_common/backtrace.rs[0m:[35m141[0m
   8: [32mrust_begin_unwind[0m[90m<unknown>[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m517[0m
   9: [32mcore::panicking::panic_fmt[0m[90m::hf66748387d5ff676[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/core/src/panicking.rs[0m:[35m101[0m
  10: [32mcore::result::unwrap_failed[0m[90m::heeb6396e1f906db0[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/core/src/result.rs[0m:[35m1617[0m
  11: [32mcore::result::Result<T,E>::expect[0m[90m::hf15ac1237d7fa0e3[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
  12: [91mbranchless::commands::main[0m[90m::h31fe288b2b696b9f[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
  13: [32mstd::sys_common::backtrace::__rust_begin_short_backtrace[0m[90m::h9013f4972cfd1e23[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
  14: [32mstd::rt::lang_start::{{closure}}[0m[90m::hea3f1e3cb83db06d[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m
  15: [32mcore::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once[0m[90m::h8403429a622a77b6[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/core/src/ops/function.rs[0m:[35m259[0m
  16: [32mstd::panicking::try::do_call[0m[90m::hb3300ca68d979c3c[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m403[0m
  17: [32mstd::panicking::try[0m[90m::h99079dac8dd742de[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m367[0m
  18: [32mstd::panic::catch_unwind[0m[90m::h5c82c9202c92574b[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panic.rs[0m:[35m129[0m
  19: [32mstd::rt::lang_start_internal::{{closure}}[0m[90m::h4b4d3cec192fefc5[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/rt.rs[0m:[35m45[0m
  20: [32mstd::panicking::try::do_call[0m[90m::hb7097b4c5e2cafa7[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m403[0m
  21: [32mstd::panicking::try[0m[90m::h8058a26d87d74c3d[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panicking.rs[0m:[35m367[0m
  22: [32mstd::panic::catch_unwind[0m[90m::he5cdfef2bb12186b[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/panic.rs[0m:[35m129[0m
  23: [32mstd::rt::lang_start_internal[0m[90m::h33c6249c3be62eca[0m
      at [35m/rustc/e6e620e1c7e7257babdfaed5c3bccbb654e72e83/library/std/src/rt.rs[0m:[35m45[0m
  24: [32m_main[0m[90m<unknown>[0m
      at [35m<unknown source file>[0m:[35m<unknown line>[0m

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```
</details

**Comment by arxanas** [comment] 2021-10-18 14:32
Thanks for the report. I'll take a look when I have a moment. Rebasing directly onto origin/master is intended to be a 100% supported use-case; I do it every day.

I suspect that this issue might incidentally be fixed by https://github.com/arxanas/git-branchless/commit/b6726d88830fb0f9fa091e789848fd8c9b07d9b2 for your use-case (you can install from source of you want to pick this commit up), but it probably doesn't work for arbitrary remote branches.

If you set

```
$ git config branchless.core.mainBranch origin/master
```

then that should amount to the same fix as above. Will elaborate later.

**Comment by arxanas** [comment] 2021-10-18 16:29
Thanks for the detailed bug report. I was able to reproduce it with these steps:

```
$ git clone https://github.com/cormacrelf/rust --branch git-move-issue
$ cd rust
$ git branchless init
$ git branch master 1067e2ca5e9cfe5c79f956e49ffc684c5142d49b
$ git move -d origin/master
...panics...
$
```

It also succeeds in a couple of seconds if I set the main branch to `origin/master`:

```
$ git config branchless.core.mainBranch origin/master
$ git move -d origin/master                          
Attempting rebase in-memory...
[1/26] Committed as: 4481d9ee intro hir::LetExpr and type check it like a hir::Local
[2/26] Committed as: 25d113eb fix attribute aliasing in let-else
[3/26] Committed as: cafa8b94 add passing test for moved expressions in if-let
[4/26] Committed as: 6e28f0a5 use hir::LetExpr in clippy
[5/26] Committed as: 52be10b6 Also use let-else type annotation when the pattern contains ref bindings
[6/26] Committed as: 441703e8 fix missing colon in pretty printed LetExpr
[7/26] Committed as: 250717f7 fix clippy format using `cargo fmt -p clippy_{lints,utils}`
[8/26] Committed as: 3f334b60 manually revert rustfmt line truncations
[9/26] Committed as: 0b59a928 rename hir::LetExpr.scrutinee => expr
[10/26] Committed as: 5d2456f5 rename hir::LetExpr => hir::Let
[11/26] Committed as: c268e6e5 reorder intravisit::walk_let_expr to what it was before
[12/26] Committed as: c058b013 document hir::Let
[13/26] Committed as: 12a99956 rename the function in the nomove test
[14/26] Committed as: 42babede use `both` instead of eq_opt_ty
[15/26] Committed as: ebb3446b Undo the shadowing of various `expr` variables after renaming `scrutinee`
[16/26] Committed as: 2b4068a1 reduce destructuring of hir::Let to avoid `expr` collisions
[17/26] Committed as: a35b04bf rename hir::Let.expr => init
[18/26] Committed as: dcbdacc9 Add failing test let-else-deref-coercion
[19/26] Committed as: b8f8e768 align typeck checking of hir::Local and hir::Let
[20/26] Committed as: 027eb0b1 revert changes to demand_scrutinee_type
[21/26] Committed as: 6b92ae4a unify typeck of hir::Local and hir::Let
[22/26] Committed as: 524ab18d fix comment in let-else test
[23/26] Committed as: c5ffa5cf fix typo
[24/26] Committed as: fce22d85 Add let-else test for pulling a copy type out of a non-copy
[25/26] Committed as: 73b28ca2 add a bunch of tests adapted from rfc2005 and elsewhere
[26/26] Committed as: 4c4ff6a7 add test for issue 89960
branchless: processing 1 update: branch git-move-issue
branchless: processing 26 rewritten commits
branchless: running command: git checkout git-move-issue
Previous HEAD position was 38ba92f0a5a add test for issue 89960
Switched to branch 'git-move-issue'
Your branch and 'origin/git-move-issue' have diverged,
and have 91 and 26 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
branchless: processing checkout
In-memory rebase succeeded.
```

However, it didn't succeed when I tried using a build with commit https://github.com/arxanas/git-branchless/commit/b6726d88830fb0f9fa091e789848fd8c9b07d9b2.

`git-branchless` keeps its own DAG structure on disk to help it answer certain graph queries, such as "what are the descendants of this node?". By default, `git-branchless` checks all of the local branches, the `HEAD` reference, and the main branch (in case it's not a local branch), and updates the DAG with any new commits that it's found. When you write `git move --dest <commit>`, where `<commit>` is not reachable from one of the previous objects, then `git-branchless` will fail with this error.

`git-move` currently has (hacky) logic to ensure that the DAG is updated with the argument to `--source`, but it's missing an equivalent for `--dest`:

https://github.com/arxanas/git-branchless/blob/62bafe36b4e1a9f1d576e5a4505e72156bb468e4/src/commands/move.rs#L109-L114

Fortunately, the `FIXME` comment there can be resolved now, probably by calling `Dag::sync_from_oids`:

https://github.com/arxanas/git-branchless/blob/62bafe36b4e1a9f1d576e5a4505e72156bb468e4/src/git/dag.rs#L197-L204

as part of the call to `resolve_commits`, which converts the name `origin/master` into a commit ID:

https://github.com/arxanas/git-branchless/blob/62bafe36b4e1a9f1d576e5a4505e72156bb468e4/src/git/dag.rs#L531-L537

**Closed as completed** 2021-10-20 02:03 UTC
Labels: bug

**Comment by arxanas** [comment] 2021-10-20 02:04
This should be fixed in https://github.com/arxanas/git-branchless/commit/7481a25b6adcce5c4a034995906ab1d1deb76af6.  You can install the latest version from source (`cargo install --locked --git https://github.com/arxanas/git-branchless`) to pick up the change.
